- apps/guest/src/login/login.component.ts
- apps/guest/src/services/guest.service.ts
[SHTL-151](https://pappcorn.atlassian.net/browse/SHTL-151)
Si ya pasó la fecha de salida el huésped, no debe poder entrar a su cuenta
> [SHTL-151] problema con fecha de salida

- apps/guest/src/reservation/page/my-reservations/my-reservations.component.html
- apps/guest/src/reservation/page/my-reservations/my-reservations.component.scss
- apps/guest/src/reservation/page/my-reservations/my-reservations.component.ts
[SHTL-154](https://pappcorn.atlassian.net/browse/SHTL-154)
Adjustment is made in the component to show reservation availability message.
> [SHTL-154] Show availability message

- apps/guest/src/reservation/page/my-reservations/my-reservations.component.html
- apps/guest/src/reservation/page/my-reservations/my-reservations.component.scss
- apps/guest/src/reservation/page/my-reservations/my-reservations.component.ts
- apps/hotel/src/home/home-routing.module.ts
- apps/hotel/src/inmediate-requests/page/inmediate-requests/inmediate-requests.component.html
- apps/hotel/src/material/components/menu/menu.component.ts
- apps/hotel/src/restaurant/components/directives/edit-mode.directive.ts
- apps/hotel/src/restaurant/components/directives/view-mode.directive.ts
- apps/hotel/src/restaurant/components/editable/editable.component.ts
- apps/hotel/src/restaurant/page/restaurant/restaurant.component.html
- apps/hotel/src/restaurant/page/restaurant/restaurant.component.scss
- apps/hotel/src/restaurant/page/restaurant/restaurant.component.spec.ts
- apps/hotel/src/restaurant/page/restaurant/restaurant.component.ts
- apps/hotel/src/restaurant/restaurant-routing.module.ts
- apps/hotel/src/restaurant/retaurant.module.ts
- apps/hotel/src/special-requests/page/special-requests/special-requests.component.html
- libs/core/src/index.ts
- libs/core/src/lib/services/restaurant/restaurant.service.ts
[SHTL-153](https://pappcorn.atlassian.net/browse/SHTL-153)
##En el administrador, en las solicitudes, debe verse el nombre completo del huésped
Adjustment is made to display the full name in the components of requests.
- Solicitudes especiales:
- Solicitudes inmediatas:
> [SHTL-153] Change to display full name

- apps/guest/src/late-check-out/late-check-out.component.html
[SHTL-161](https://pappcorn.atlassian.net/browse/SHTL-161)
- Change Label
> [SHTL-161] Change Label

- apps/hotel/src/reservation/pages/schedule/schedule.component.ts
- libs/const/days.ts
[SHTL-148](https://pappcorn.atlassian.net/browse/SHTL-148)
- Selección de zona de reserva diaria:
- Generación de espacios de reserva automáticos:
> [SHTL-148] Generate ranges of available spaces

- apps/hotel/src/reservation/pages/schedule/schedule.component.ts
[SHTL-148](https://pappcorn.atlassian.net/browse/SHTL-148)
##Como un administrador necesito elegir la disponibilidad de un espacio para reserva para todos los días así podré crearlos más rápidamente
- no debería borrar los bloques que ya estén guardados
bloque existente
Generación de bloque con bloques existentes.
> [SHTL-148]  Adjustment in the generation of massive reserve zone ranges

- apps/guest/src/reservation/page/create-reservation/create-reservation.component.ts
[SHTL-154](https://pappcorn.atlassian.net/browse/SHTL-154)
- Informar al usuario sobre la disponibilidad en las reservas.
- Agregar validación para verificar disponibilidad.
- Mostrar mensaje informativo.
- Mensaje:
> [SHTL-154] Informational message of availability

- apps/guest/src/reservation/page/create-reservation/create-reservation.component.html
- apps/guest/src/reservation/page/create-reservation/create-reservation.component.ts
- libs/const/index.ts
- libs/const/type-errors.ts
[SHTL-180](https://pappcorn.atlassian.net/browse/SHTL-180)
Se realiza ajuste para permitir mostrar los dias disponibles dentro del calendario
> [SHTL-180] Availability of dates

- apps/guest/src/home/home-routing.module.ts
- apps/guest/src/home/pages/guest-requests/guest-requests.component.html
- apps/guest/src/home/pages/guest-requests/guest-requests.component.ts
- apps/guest/src/home/pages/zone-request/const/zone-const.ts
- apps/guest/src/home/pages/zone-request/zone-request.component.scss
- apps/guest/src/home/pages/zone-request/zone-request.component.ts
- apps/guest/src/my-room/my-room.component.html
- apps/guest/src/my-room/my-room.component.scss
- apps/guest/src/my-room/my-room.component.ts
- apps/guest/src/my-room/my-room.module.ts
- apps/guest/src/my-room/my-room.routing.module.ts
- apps/guest/src/my-room/pages/maintenance/maintenance.component.html
- apps/guest/src/my-room/pages/maintenance/maintenance.component.scss
- apps/guest/src/my-room/pages/maintenance/maintenance.component.spec.ts
- apps/guest/src/my-room/pages/maintenance/maintenance.component.ts
- apps/hotel/src/common-components/modal-inmediate-request/modal-inmediate-request.component.ts
- libs/const/category-zone.ts
- libs/core/src/index.ts
- libs/core/src/lib/core.module.ts
- libs/core/src/lib/services/room-service/index.ts
- libs/core/src/lib/services/room-service/room-key.service.ts
- libs/core/src/lib/services/room-service/room.service.spec.ts
- libs/core/src/lib/services/room-service/room.service.ts
- libs/models/index.ts
- libs/models/maintenance.model.ts
- libs/models/room-key.model.ts
[SHTL-166](https://pappcorn.atlassian.net/browse/SHTL-166)
Se crea componente
Se crea servicio
Se crea modelo
Se añade funcionalidad y métodos para crear mantenimiento
> [SHTL-166] Schedule maintenance

- apps/guest/src/my-room/const/cleaning.const.ts
- apps/guest/src/my-room/my-room.module.ts
- apps/guest/src/my-room/my-room.routing.module.ts
- apps/guest/src/my-room/pages/cleaning/cleaning.component.html
- apps/guest/src/my-room/pages/cleaning/cleaning.component.scss
- apps/guest/src/my-room/pages/cleaning/cleaning.component.spec.ts
- apps/guest/src/my-room/pages/cleaning/cleaning.component.ts
- apps/guest/src/my-room/pages/maintenance/maintenance.component.ts
- libs/const/category-zone.ts
- libs/core/src/lib/core.module.ts
- libs/core/src/lib/services/room-service/index.ts
- libs/core/src/lib/services/room-service/room-cleaning.service.ts
- libs/models/cleaning.model.ts
- libs/models/index.ts
- libs/models/room-key.model.ts
[SHTL-165](https://pappcorn.atlassian.net/browse/SHTL-165)
Se crea componente.
Se añaden estilos.
Se crea servicio.
Se crea modelo.
Se añade funcionalidad
> [SHTL-165] request or schedule cleaning of my room

- apps/mobile/src/app/order/components/item/item.component.html
- apps/mobile/src/app/order/pages/order-detail/order-detail.component.html
[SHTL-183](https://pappcorn.atlassian.net/browse/SHTL-183)
Agregar variable para asignar el nombre completo
> [SHTL-183] Put full name of who made the order

- apps/hotel/src/reservation/pages/calendar/calendar.component.html
- apps/hotel/src/reservation/pages/calendar/calendar.component.scss
- apps/hotel/src/reservation/pages/calendar/calendar.component.ts
- apps/hotel/src/utils/const/month.ts
- apps/hotel/src/utils/returnMonth.ts
- Agregar carpeta de utilidades.
- Creación de método para obtener el mes actual.
- Ajuste de componente para agregar el mes.
Cambio de mes:
> [SHTL-188] Reservation calendar

- apps/hotel/src/order/pages/view-order/view-order.component.html
- apps/hotel/src/order/pages/view-order/view-order.component.scss
- apps/hotel/src/order/pages/view-order/view-order.component.ts
- Ajustar componente.
- Agregar variable para setear nombre de restaurante del producto.
- Agregar estilos.
> [SHTL-186] Restaurant name of products

- apps/hotel/src/wake-up/wake-up.component.html
- apps/hotel/src/wake-up/wake-up.component.ts
- libs/models/wakeTable.ts
[SHTL-214](https://pappcorn.atlassian.net/browse/SHTL-214)
- Ajuste de componente para mostrar en la lista el nombre de la persona que se debe llamar
> [SHTL-214] Show name of person to call

- apps/hotel/src/reservation/pages/calendar/calendar.component.ts
- Agregar el numero de personas en las reservas.
> [SHTL-190]  Add number of people in the reservation

- apps/guest/src/home/pages/drink-request/drink-request.component.ts
- apps/guest/src/home/pages/inmediate-request/inmediate-request.component.ts
- apps/guest/src/home/pages/special-request/special-request.component.ts
- apps/guest/src/home/pages/zone-request/zone-request.component.ts
- apps/guest/src/services/messages/messages.service.ts
[SHTL-208](https://pappcorn.atlassian.net/browse/SHTL-208)
- Traducir texto de solicitud inmediata creada exitosamente a ingles.
- Cambio de otros textos de español a ingles.
> [SHTL-208] Translate texts

- apps/guest/src/home/components/modal-qualify/modal-qualify.component.html
[SHTL-203](https://pappcorn.atlassian.net/browse/SHTL-203)
- Se ajustan los labels del enunciado y del input
> [SHTL-203] Change of labels

- apps/guest/src/reservation/page/create-reservation/create-reservation.component.ts
[SHTL-206](https://pappcorn.atlassian.net/browse/SHTL-206)
- Ajuste de componente para agregar mensaje de confirmación de reserva creada
> [SHTL-206] Confirmation message

- apps/guest/src/home/pages/create-wake/create-wake.component.html
- apps/guest/src/home/pages/create-wake/create-wake.component.ts
[SHTL-210](https://pappcorn.atlassian.net/browse/SHTL-210)
- Ajuste de componente.
- Refactorización de código.
> [SHTL-210] Huésped - Cuando creo un wakeup call, el botón de "create request" sale con texto negro sobre fondo azul. 

- apps/mobile/src/app/wake-up/components/wake/wake.component.scss
- apps/mobile/src/app/wake-up/pages/wake-complete/wake-complete.component.scss
- apps/mobile/src/app/wake-up/pages/wake-pending/wake-pending.component.scss
[SHTL-211](https://pappcorn.atlassian.net/browse/SHTL-211)
- Ajustes de estilos entre las solicitudes
Solicitudes pendientes:
Solicitudes resueltas:
> [SHTL-211] App - En los wakeup calls, revisar los estilos, puntualmente el margin entre una solicitud y la otra

- apps/mobile/src/app/modals/modal-inmediate-request/modal-inmediate-request.page.html
[SHTL-202](https://pappcorn.atlassian.net/browse/SHTL-202)
- Agregar placeholder del campo Empleado de las solicitudes inmediatas.
> [SHTL-202] App - Adentro de la solicitud inmediata no se ve el título del placeholder "empleado"

- apps/hotel/src/inmediate-requests/page/inmediate-requests/inmediate-requests.component.html
- Ajuste de componente HTML para no mostrar datos demas.
> [SHTL-205] Admin - En las solicitudes especiales, al lado del nombre dle huésped sale un número "Lina bustamante 16" qué es? Quitémoslo 

- apps/hotel/src/common-components/common-components.module.ts
- apps/hotel/src/common-components/modal-inmediate-request/modal-inmediate-request.component.html
[SHTL-207](https://pappcorn.atlassian.net/browse/SHTL-207)
- Ajuste del componente que muestra el score.
> [SHTL-207] Admin - En las solicitudes inmediatas, una vez cumplidas, no se ven las estrellas, solo el mensaje

- apps/mobile/src/app/booking/booking.component.html
- apps/mobile/src/app/booking/booking.component.ts
- apps/mobile/src/app/booking/booking.module.ts
- apps/mobile/src/app/booking/components/modal-confirm/modal-confirm.component.html
- apps/mobile/src/app/wake-up/components/modal-confirm-wake/modal-confirm-wake.component.html
- apps/mobile/src/app/wake-up/components/modal-confirm-wake/modal-confirm-wake.component.ts
- apps/mobile/src/app/wake-up/wake-up.module.ts
- Ajuste de estilos y refactorización de código.
> [SHTL-212] App - En el popup de confirmación si ya se hizo el wakeup call, el botón azul no se lee qué dice

- libs/core/src/lib/services/product.service.ts
[SHTL-201](https://pappcorn.atlassian.net/browse/SHTL-201)
- Ajuste de componente.
- Agregar métodos para envió de notificación push.
> [SHTL-201] App - Las notificaciones de pedidos no están llegando

- apps/guest/src/late-check-out/modal/create-late/create-late.component.ts
- apps/guest/src/reservation/page/create-reservation/create-reservation.component.ts
- apps/guest/src/services/messages/messages.service.ts
[SHTL-216](https://pappcorn.atlassian.net/browse/SHTL-216)
- Cambio del label cerrar a close en los toast
> [SHTL-216] Huésped - Todos los Toast dicen cerrar, cambiar a close

- apps/guest/src/home/components/modal-booking-qualify/modal-booking-qualify.component.ts
- apps/guest/src/home/components/modal-orders-quialify/modal-orders-quialify.component.ts
- apps/guest/src/home/components/modal-qualify/modal-qualify.component.ts
- apps/guest/src/pipes/score-label.pipe.ts
[SHTL-218]()
- Cambio de labels de español a ingles cuando se califica un servicio.
> [SHTL-218] Huésped - Cuando califico, elijo las estrellas, sale la calificación en español.. ejemplo "Excelente" 

- apps/mobile/src/app/modals/modal-special-request/modal-special-request.page.html
- apps/mobile/src/app/modals/modal-special-request/modal-special-request.page.ts
[SHTL-219](https://pappcorn.atlassian.net/browse/SHTL-219)
- Ajuste para devolverse en la modal de solicitudes especiales
> [SHTL-219] App - Cuando entro a una solicitud Especial, no funciona el botón de back

- apps/mobile/src/app/modals/modal-special-request/modal-special-request.page.html
- apps/mobile/src/app/modals/modal-special-request/modal-special-request.page.ts
[SHTL-220]()
- Agregar funcionalidad para mostrar el logo que tenga el hotel configurado.
> [SHTL-220] App - Dentro de una solicitud especial aparece el logo del hotel de prueba

- apps/hotel/src/home/page/admin-home/admin-home.component.ts
[SHTL-221](https://pappcorn.atlassian.net/browse/SHTL-221)
* Opciones que deben de aparecer: Huéspedes - Solicitudes Inmediatas - Recepción - Zonas - Reservas de espacios - 
Restaurantes - Empleados - Solicitudes Especiales - Late Checkouts
* Ajuste del menú principal - organización
> [SHTL-221] Admin - En el home donde aparecen 9 opciones de acceso.

- apps/hotel/src/guest/components/modal-edit-guest/modal-edit-guest.component.html
- apps/hotel/src/guest/components/modal-edit-guest/modal-edit-guest.component.ts
- libs/entity/guest.entity.ts
[SHTL-223](https://pappcorn.atlassian.net/browse/SHTL-223)
- Se realiza ajuste para permitir enviar email al servicio de creación y actualización de huéspedes
> [SHTL-223] Admin - Que en el perfil se pueda ver el correo del huésped

- apps/hotel/src/common-components/modal-edit-employer/modal-edit-employer.component.html
- apps/hotel/src/common-components/modal-edit-employer/modal-edit-employer.component.ts
- libs/entity/employer.entity.ts
[SHTL-224](https://pappcorn.atlassian.net/browse/SHTL-224)
* Agregar campo de email en la vista de edición de empleado
> [SHTL-224] Admin - Que en el perfil se pueda ver el correo del empleado

- apps/guest/src/common-components/common-components.module.ts
- apps/guest/src/common-components/marco/marco.component.html
- apps/guest/src/common-components/marco/marco.component.ts
- apps/guest/src/common-components/sidebar/sidebar.component.html
- apps/guest/src/common-components/sidebar/sidebar.component.ts
- apps/mobile/src/app/booking/booking.component.html
- apps/mobile/src/app/clean/clean.component.html
- apps/mobile/src/app/common-components/common-components.module.ts
- apps/mobile/src/app/common-components/logo/logo.component.html
- apps/mobile/src/app/common-components/logo/logo.component.scss
- apps/mobile/src/app/common-components/logo/logo.component.ts
- apps/mobile/src/app/home/home.page.html
- apps/mobile/src/app/home/home.page.ts
- apps/mobile/src/app/home/inmediate-requests/pending-inmediate-requests/pending-inmediate-requests.page.html
- apps/mobile/src/app/home/inmediate-requests/ready-inmediate-requests/ready-inmediate-requests.page.html
- apps/mobile/src/app/home/special-requests/active-special-requests/active-special-requests.page.html
- apps/mobile/src/app/home/special-requests/past-special-requests/past-special-requests.page.html
- apps/mobile/src/app/latecheck-out/latecheck-out.component.html
- apps/mobile/src/app/latecheck-out/latecheck-out.module.ts
- apps/mobile/src/app/maintain/maintain.component.html
- apps/mobile/src/app/modals/modal-special-request/modal-special-request.page.html
- apps/mobile/src/app/order/order.module.ts
- apps/mobile/src/app/order/pages/order-complete/order-complete.component.html
- apps/mobile/src/app/order/pages/order-detail/order-detail.component.html
- apps/mobile/src/app/order/pages/order-pending/order-pending.component.html
- apps/mobile/src/app/reception/reception.component.html
- apps/mobile/src/app/statistic/statistic.component.html
- apps/mobile/src/app/statistic/statistic.module.ts
- apps/mobile/src/app/wake-up/pages/wake-complete/wake-complete.component.html
- apps/mobile/src/app/wake-up/pages/wake-pending/wake-pending.component.html
[SHTL-231](https://pappcorn.atlassian.net/browse/SHTL-231)
- Ajustes de componentes.
- Agregar funcionalidad para el redireccionamiento al home del App y Guest.
- Re-ajuste del componente del logo en el app para darle funcionalidad requerida.
- Re-utilización de componente de logo en App.
APP:
GUEST:
> [SHTL-231] App y huésped - Al hacer clic en el logo que regrese al home

- apps/hotel/src/inmediate-requests/components/request/request.component.ts
[SHTL-228](https://pappcorn.atlassian.net/browse/SHTL-228)
- Se realiza ajuste al componente para actualizar la información de las solicitudes inmediatas.
- Refactorización de código.
> [SHTL-228] Admin - Cuando edito la solicitud inmediata (empleado o estado) y le doy guardar no aparece, debo refrescar la página. 

- apps/hotel/src/home/page/admin-home/admin-home.component.html
- apps/hotel/src/home/page/admin-home/admin-home.component.ts
- apps/hotel/src/inmediate-requests/page/inmediate-requests/inmediate-requests.component.ts
[SHTL-221](https://pappcorn.atlassian.net/browse/SHTL-221)
- Ajuste de los badges del menú principal.
- Agregar enrutamiento con filtro en el menú principal de recepción.
- Ajuste de componente y validación de rutas.
> [SHTL-221] Admin - En el home donde aparecen 9 opciones de acceso debemos dejar las siguientes: 

- apps/guest/src/app/app-routing.module.ts
- apps/guest/src/app/app.component.ts
- apps/guest/src/app/app.module.ts
- apps/guest/src/common-components/common-components.module.ts
- apps/guest/src/common-components/guards/avalible-user.guard.ts
[SHTL-229](https://pappcorn.atlassian.net/browse/SHTL-229)
- Ajuste para verificar si el huésped tiene la fecha de salida vigente cuando se recarga la pagina
- Agregar método que valide si el usuario tiene la fecha de salida vigente al recargar la pantalla.
Fecha de salida:
Ingreso huésped con fecha de salida vigente:
Cambio de fecha de salida:
Recargar pagina para validación de fecha de saluda del usuario:
> [SHTL-229] Huésped - Si estoy logueado como un huésped, y se pasa mi fecha de salida, igual puedo seguir pidiendo cosas.

- apps/hotel/src/material/components/interfaces/children-menu.interface.ts
- apps/hotel/src/material/components/interfaces/item-menu.interface.ts
- apps/hotel/src/material/components/menu-list-item/menu-list-item.component.html
- apps/hotel/src/material/components/menu-list-item/menu-list-item.component.scss
- apps/hotel/src/material/components/menu-list-item/menu-list-item.component.spec.ts
- apps/hotel/src/material/components/menu-list-item/menu-list-item.component.ts
- apps/hotel/src/material/components/menu/menu.component.html
- apps/hotel/src/material/components/menu/menu.component.ts
- apps/hotel/src/material/material.module.ts
[SHTL-230](https://pappcorn.atlassian.net/browse/SHTL-230)
- Ajuste de componente.
- Se agrega nuevo componente relacionado al menú.
- Se agrega funcionalidad que me permita el manejo de sub-menús.
> [SHTL-230] Como un administrador necesito ver el menú agrupado así podré navegarlo más fácil

- apps/hotel/src/employer/employer.module.ts
- apps/hotel/src/employer/page/employer/employer.component.html
- apps/hotel/src/employer/page/employer/employer.component.scss
[SHTL-233](https://pappcorn.atlassian.net/browse/SHTL-233)
* Ajuste de componente.
* Ajuste de estilos del componente.
* Agregar botón para ver calificaciones en la vista de empleado.
> [SHTL-233] Como un administrador necesito acceder a las calificaciones de los empleados desde la sección de empleados así podré llegar rápidamente

- apps/hotel/src/guest/page/guest/guest.component.html
- apps/hotel/src/material/material.module.ts
- apps/hotel/src/zone/components/modal-edit-zone/modal-edit-zone.component.html
- apps/hotel/src/zone/components/modal-edit-zone/modal-edit-zone.component.ts
- apps/hotel/src/zone/page/zone/zone.component.html
- apps/hotel/src/zone/page/zone/zone.component.scss
- apps/hotel/src/zone/page/zone/zone.component.ts
[SHTL-235]()
* Ajuste para editar zonas principales.
* Validar zonas principales.
* Ajuste de componentes.
Ajuste encabezado de huéspedes en la grid:
> [SHTL-235] Como un administrador necesito editar las zonas destacadas así podré actualizar cuáles quiero que sean las principales.

- apps/hotel/src/guest/guest.module.ts
- apps/hotel/src/guest/page/guest/guest.component.html
- apps/hotel/src/guest/page/guest/guest.component.ts
[SHTL-238](https://pappcorn.atlassian.net/browse/SHTL-238)
* Ajuste de filtros
> [SHTL-238] Admin - Huéspedes - No funciona el filtro de Activo - Inactivos

- apps/hotel/src/guest/guest.module.ts
- apps/hotel/src/guest/page/guest/guest.component.html
- apps/hotel/src/guest/page/guest/guest.component.ts
Reverts Contler/monorepo-web#92
> Revert "[SHTL-238] Admin - Huéspedes - No funciona el filtro de Activo - Inactivos"

- apps/mobile/src/app/booking/booking.component.html
[SHTL-245](https://pappcorn.atlassian.net/browse/SHTL-245)
* Ajustar y agregar nombre y numero de habitación de la reserva
> [SHTL-245] App - Reservas - ver el nombre del huésped y la habitación

- apps/mobile/src/app/statistic/components/card-employees/card-employees.component.html
- apps/mobile/src/app/statistic/components/card-employees/card-employees.component.scss
- apps/mobile/src/app/statistic/statistic.component.scss
[SHTL-248](https://pappcorn.atlassian.net/browse/SHTL-248)
* Ajuste de componente.
> [SHTL-248] App - Estadísticas - Ocultar el botón "perfil completo"

- apps/hotel/src/guest/components/modal-edit-guest/modal-edit-guest.component.html
- apps/hotel/src/guest/components/modal-edit-guest/modal-edit-guest.component.scss
- apps/hotel/src/guest/components/modal-edit-guest/modal-edit-guest.component.ts
[SHTL-251](https://pappcorn.atlassian.net/browse/SHTL-251)
* Ajustes de componente.
* Agregar sección de solicitudes especiales en la modal de huésped.
* Agregar funcionalidad.
> [SHTL-251] Como un administrador necesito ver las solicitudes especiales dentro del perfil del usuario así podré leerlo rápidamente 

- apps/guest/src/home/pages/zone-request/const/zone-const.ts
- apps/guest/src/home/pages/zone-request/zone-request.component.ts
[SHTL-242]()
* Ajuste de componente.
* Agregar nuevas constantes de validación.
> [SHTL-242] Huésped - Al elegir la zona "pool" adentro dice "You are in Zonas húmedas" revisar por qué llama a la categoría principal y el espanglish.

- apps/mobile/src/app/common-components/reception-item/reception-item.component.html
- apps/mobile/src/app/common-components/request-reception/request-reception.component.html
[SHTL-250](https://pappcorn.atlassian.net/browse/SHTL-250)
* Agregar fecha de creación en solicitudes de recepción, mantenimiento y limpieza.
* Ajuste de componentes.
* Organización componentes HTML.
> [SHTL-250] App - Mantenimiento/Limpieza/recepción sumar la fecha de la solicitud afuera y dentro del card. 

- apps/mobile/src/app/booking/booking-routing.module.ts
- apps/mobile/src/app/booking/booking.component.html
- apps/mobile/src/app/booking/booking.component.ts
- apps/mobile/src/app/booking/booking.module.ts
- apps/mobile/src/app/booking/pages/pending-booking/pending-bookin-routing.module.ts
- apps/mobile/src/app/booking/pages/pending-booking/pending-booking.component.html
- apps/mobile/src/app/booking/pages/pending-booking/pending-booking.component.scss
- apps/mobile/src/app/booking/pages/pending-booking/pending-booking.component.ts
- apps/mobile/src/app/booking/pages/pending-booking/pending-booking.module.ts
- apps/mobile/src/app/booking/pages/ready-booking/ready-booking-routing.module.ts
- apps/mobile/src/app/booking/pages/ready-booking/ready-booking.component.html
- apps/mobile/src/app/booking/pages/ready-booking/ready-booking.component.scss
- apps/mobile/src/app/booking/pages/ready-booking/ready-booking.component.ts
- apps/mobile/src/app/booking/pages/ready-booking/ready-booking.module.ts
- libs/core/src/lib/services/reservation.service.ts
[SHTL-244](https://pappcorn.atlassian.net/browse/SHTL-244)
* Ajuste y refactorización de código.
* Agregar nuevos componentes.
* Ajustar componentes HTML.
> [SHTL-244] App - Reservas - Al hacer clic en confirmar o cancelar, no se debe eliminar, debe seguir visible con el estado "confirmado" "Cancelado".

- apps/guest/src/assets/i18n/en-US.json
- apps/guest/src/assets/i18n/es-CO.json
- apps/guest/src/home/components/const/qualify.const.ts
- apps/guest/src/home/components/modal-booking-qualify/modal-booking-qualify.component.html
- apps/guest/src/home/components/modal-booking-qualify/modal-booking-qualify.component.ts
- apps/guest/src/home/components/modal-orders-quialify/modal-orders-quialify.component.html
- apps/guest/src/home/components/modal-orders-quialify/modal-orders-quialify.component.ts
- apps/guest/src/home/components/modal-qualify/modal-qualify.component.html
- apps/guest/src/home/components/modal-qualify/modal-qualify.component.ts
- apps/guest/src/home/home.module.ts
- apps/guest/src/home/pages/create-wake/create-wake.component.html
- apps/guest/src/home/pages/create-wake/create-wake.component.ts
- apps/guest/src/home/pages/drink-request/drink-request.component.html
- apps/guest/src/home/pages/drink-request/drink-request.component.ts
- apps/guest/src/home/pages/guest-requests/guest-requests.component.html
- apps/guest/src/home/pages/inmediate-request/inmediate-request.component.html
- apps/guest/src/home/pages/inmediate-request/inmediate-request.component.ts
- apps/guest/src/home/pages/my-inmediate-requests/my-inmediate-requests.component.html
- apps/guest/src/home/pages/special-request/special-request.component.html
- apps/guest/src/home/pages/special-request/special-request.component.ts
- apps/guest/src/home/pages/wake-up/wake-up.component.html
- apps/guest/src/home/pages/zone-request/zone-request.component.html
- apps/guest/src/home/pages/zone-request/zone-request.component.ts
- apps/guest/src/product/product.component.ts
Next branch I will work with pages componets
> Feat/add translate home (components)

- apps/hotel/src/assets/i18n/de-DE.json
- apps/hotel/src/assets/i18n/en-US.json
- apps/hotel/src/assets/i18n/es-CO.json
- apps/hotel/src/assets/i18n/fr-FR.json
- apps/hotel/src/assets/i18n/it-IT.json
- apps/hotel/src/assets/i18n/pt-PT.json
- apps/hotel/src/inmediate-requests/components/reception-request/reception-request.component.ts
- apps/hotel/src/inmediate-requests/const/request.const.ts
- Filters added transportation, concierge, currency exchange
and cash loan
Loom: 
https://www.loom.com/share/8075bdcb086e4e4abaabac166a41b0da
> SHTL-274 Como un administrador de hotel necesito filtrar las solicitudes de recepción en el dash así podré diferenciarlas

- apps/admin/src/app/home/pages/hotel/hotel.component.ts
- apps/hotel/src/assets/i18n/de-DE.json
- apps/hotel/src/assets/i18n/en-US.json
- apps/hotel/src/assets/i18n/es-CO.json
- apps/hotel/src/assets/i18n/fr-FR.json
- apps/hotel/src/assets/i18n/it-IT.json
- apps/hotel/src/assets/i18n/pt-PT.json
- apps/hotel/src/common-components/modal-loader/loader.component.html
- apps/hotel/src/common-components/modal-loader/loader.component.scss
- apps/hotel/src/common-components/modal-loader/loader.component.spec.ts
- apps/hotel/src/common-components/modal-loader/loader.component.ts
- apps/hotel/src/preferences/components/module-card/module-card.component.html
- apps/hotel/src/preferences/components/module-card/module-card.component.scss
- apps/hotel/src/preferences/components/module-card/module-card.component.spec.ts
- apps/hotel/src/preferences/components/module-card/module-card.component.ts
- apps/hotel/src/preferences/pages/module-list/models/module.ts
- apps/hotel/src/preferences/pages/module-list/module-list.component.html
- apps/hotel/src/preferences/pages/module-list/module-list.component.scss
- apps/hotel/src/preferences/pages/module-list/module-list.component.spec.ts
- apps/hotel/src/preferences/pages/module-list/module-list.component.ts
- apps/hotel/src/preferences/pages/welcome/welcome.component.html
- apps/hotel/src/preferences/pages/welcome/welcome.component.ts
- apps/hotel/src/preferences/preferences-routing.module.ts
- apps/hotel/src/preferences/preferences.module.ts
- apps/hotel/src/services/messages/messages.service.ts
- libs/entity/SpecialZoneHotel.entity.ts
Enable and disabled modules while initial configuration is false
Loom :
https://www.loom.com/share/7264c40c215b4caab90b07a65f4f6bb7
> SHTL - 280 Como un admin de hotel necesito elegir los módulos que activaré en la réplica así podré definir mis servicios

- apps/hotel/src/preferences/components/module-card/module-card.component.html
- apps/hotel/src/preferences/components/module-card/module-card.component.scss
- apps/hotel/src/preferences/components/module-card/module-card.component.ts
Loom:
https://www.loom.com/share/174bbb3d51a748a8a9f4c089be945202
> Refactor - SHTL 280 - Como un admin de hotel necesito elegir los módulos que activaré en la réplica así podré definir mis servicios

- apps/guest/src/home/home.module.ts
- apps/guest/src/home/pages/zone-request/zone-item/zone-item.component.html
- apps/guest/src/home/pages/zone-request/zone-item/zone-item.component.scss
- apps/guest/src/home/pages/zone-request/zone-item/zone-item.component.spec.ts
- apps/guest/src/home/pages/zone-request/zone-item/zone-item.component.ts
- apps/guest/src/home/pages/zone-request/zone-request.component.html
- apps/guest/src/home/pages/zone-request/zone-request.component.scss
- apps/guest/src/home/pages/zone-request/zone-request.component.ts
- apps/guest/src/services/zone.service.ts
Loom: 
https://www.loom.com/share/edd904bd31164585acdac7a441ebcdab
> SHTL 288 - Como un huésped necesito pedir las solicitudes inmediatas dinámicas 

- apps/guest/src/home/pages/inmediate-request/inmediate-request.component.html
- apps/guest/src/home/pages/zone-request/zone-request.component.html
- apps/guest/src/home/pages/zone-request/zone-request.component.scss
- apps/guest/src/home/pages/zone-request/zone-request.component.ts
- apps/hotel/src/zone/page/zone/zone.component.ts
- apps/mobile/src/app/common-components/dynamic-item/dynamic-item.component.ts
- apps/mobile/src/app/common-components/dynamicresult/dynamic-result.component.html
- apps/mobile/src/app/common-components/dynamicresult/dynamic-result.component.scss
- apps/mobile/src/app/common-components/dynamicresult/dynamic-result.component.ts
from modal angular material to modal controller ionic dynamic forms dynamic result 
Loom: 
https://www.loom.com/share/6bf15436c199422cb25f63abe34f3db4
> fix error bugs translate text, re design button immediate request

- apps/guest/src/home/pages/inmediate-request/inmediate-request.component.html
- apps/guest/src/home/pages/zone-request/zone-request.component.html
- apps/guest/src/home/pages/zone-request/zone-request.component.scss
- apps/guest/src/home/pages/zone-request/zone-request.component.ts
- apps/hotel/src/restaurant/page/restaurant/restaurant.component.html
- apps/hotel/src/restaurant/page/restaurant/restaurant.component.scss
- apps/hotel/src/zone/page/zone/zone.component.ts
- apps/mobile/src/app/common-components/dynamic-item/dynamic-item.component.ts
- apps/mobile/src/app/common-components/dynamicresult/dynamic-result.component.html
- apps/mobile/src/app/common-components/dynamicresult/dynamic-result.component.scss
- apps/mobile/src/app/common-components/dynamicresult/dynamic-result.component.ts
- libs/const/languages.ts
loom: 
https://www.loom.com/share/d01b11b3a5fd450999c2a14a1830be64
>  add buttons direct access to restaurant page and change typo

- apps/hotel/src/common-components/modal-reception/modal-reception.component.ts
>  fix error from hotel set status remove set status all

- apps/admin/src/app/home/pages/hotel/hotel.component.html
- apps/admin/src/app/home/pages/hotel/hotel.component.ts
Loom:
https://www.loom.com/share/25876723313d4f32a4392246be1e2d59
> feat(admin) add button back on show hotel

- apps/admin/src/app/app.module.ts
- apps/admin/src/assets/i18n/es-CO.json
- libs/core/src/lib/components/zone-list/zone-list.component.html
- libs/core/src/lib/core.module.ts
> :bug: add translate module to super admin project

- apps/hotel/src/reception/reception.component.html
- libs/dynamic-services/src/lib/components/dynamicform/dynamic-form.component.html
- libs/dynamic-services/src/lib/components/new-input/new-input.component.html
- libs/dynamic-services/src/lib/constants/option-inputs.ts
- libs/dynamic-services/src/lib/interfaces/input-field.ts
Loom: https://www.loom.com/share/911d8c252df242a2a059a3ba4ea07402
> add option input extern url
